---
- name: "Converge"
  hosts: "local"
  tasks:

    - name: "Include labocbz.install_logwatch"
      tags:
        - "labocbz.install_logwatch"
      vars:
        install_logwatch__create_cron_job: "{{ inv_install_logwatch__create_cron_job }}"
        install_logwatch__cron_job_weekday: "{{ inv_install_logwatch__cron_job_weekday }}"
        install_logwatch__cron_job_minute: "{{ inv_install_logwatch__cron_job_minute }}"
        install_logwatch__cron_job_hour: "{{ inv_install_logwatch__cron_job_hour }}"
        install_logwatch__report_email_address: "{{ inv_install_logwatch__report_email_address }}"
        install_logwatch__output_format: "{{ inv_install_logwatch__output_format }}"
      ansible.builtin.include_role:
        name: "labocbz.install_logwatch"
