---
# Don't forget to keep this file updated
# molecule/<scenario>/verify.yml
- name: "Verify"
  hosts: "cicd-ubuntu-22"
  gather_facts: false
  tasks:

    - name: "Check if Logwatch cache exist"
      register: install_logwatch__cache
      failed_when: not install_logwatch__cache.stat.exists
      ansible.builtin.stat:
        path: "/var/cache/logwatch"

    - name: "Check if Logwatch configuration exist"
      register: install_logwatch__configuration
      failed_when: not install_logwatch__configuration.stat.exists
      ansible.builtin.stat:
        path: "/etc/logwatch/conf/logwatch.conf"

    - name: "Check if a cron file exist"
      when: inv_install_logwatch__create_cron_job
      register: cron_file
      failed_when: not cron_file.stat.exists
      ansible.builtin.stat:
        path: "/etc/cron.d/ansible_install_logwatch__send_reports"

    - name: "Create a Logwtach report and check status code"
      register: logwtach_create_report_status
      failed_when: logwtach_create_report_status.rc != 0
      changed_when: logwtach_create_report_status.rc != 0
      ansible.builtin.command: |
        logwatch --output {{ inv_install_logwatch__output_format }}
